"""Create initial leaderboard schema with cohorts

Revision ID: 97b807bfce22
Revises: 
Create Date: 2026-06-18 00:24:23.786206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '97b807bfce22'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cohort',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('student',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('workshop_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cohort_id', sa.Integer(), nullable=True),
    sa.Column('session_date', sa.Date(), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['cohort_id'], ['cohort.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('score_entry',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('student_id', sa.Integer(), nullable=False),
    sa.Column('workshop_session_id', sa.Integer(), nullable=False),
    sa.Column('present', sa.Boolean(), nullable=True),
    sa.Column('arrival_time', sa.Time(), nullable=True),
    sa.Column('meaningful_question', sa.Boolean(), nullable=True),
    sa.Column('distracts_others', sa.Boolean(), nullable=True),
    sa.Column('connects_ideas', sa.Boolean(), nullable=True),
    sa.Column('challenges_assumption', sa.Boolean(), nullable=True),
    sa.Column('learning_risk', sa.Boolean(), nullable=True),
    sa.Column('answers_question', sa.Boolean(), nullable=True),
    sa.Column('contributed_dynamic', sa.Boolean(), nullable=True),
    sa.Column('included_all', sa.Boolean(), nullable=True),
    sa.Column('allocated_tasks', sa.Boolean(), nullable=True),
    sa.Column('leadership_or_follow', sa.Boolean(), nullable=True),
    sa.Column('helped_fellow_muslim', sa.Boolean(), nullable=True),
    sa.Column('includes_others_salaam', sa.Boolean(), nullable=True),
    sa.Column('respectful_to_all', sa.Boolean(), nullable=True),
    sa.Column('on_phone_unneeded', sa.Boolean(), nullable=True),
    sa.Column('interrupts_or_disrespect', sa.Boolean(), nullable=True),
    sa.Column('completed_activity', sa.Boolean(), nullable=True),
    sa.Column('expanded_activity', sa.Boolean(), nullable=True),
    sa.Column('base_points', sa.Integer(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['student_id'], ['student.id'], ),
    sa.ForeignKeyConstraint(['workshop_session_id'], ['workshop_session.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('student_id', 'workshop_session_id', name='uniq_student_workshop_session')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('score_entry')
    op.drop_table('workshop_session')
    op.drop_table('student')
    op.drop_table('cohort')
    # ### end Alembic commands ###
